// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: mutex/v1/mutex.proto

package mutexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Mutex_RequestCS_FullMethodName = "/mutex.v1.Mutex/RequestCS"
)

// MutexClient is the client API for Mutex service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mutex is the peer-to-peer transport for Ricart-Agrawala distributed
// mutual exclusion. Nodes call each other on the same gRPC port that serves
// the client DB API.
//
// The paper's REQUEST/REPLY message pair maps onto one blocking RPC: the
// call carries the REQUEST; the response IS the grant. A node that must
// defer (it holds the CS, or its own request has priority) simply does not
// respond until it exits the critical section.
type MutexClient interface {
	RequestCS(ctx context.Context, in *RequestCSRequest, opts ...grpc.CallOption) (*RequestCSResponse, error)
}

type mutexClient struct {
	cc grpc.ClientConnInterface
}

func NewMutexClient(cc grpc.ClientConnInterface) MutexClient {
	return &mutexClient{cc}
}

func (c *mutexClient) RequestCS(ctx context.Context, in *RequestCSRequest, opts ...grpc.CallOption) (*RequestCSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestCSResponse)
	err := c.cc.Invoke(ctx, Mutex_RequestCS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MutexServer is the server API for Mutex service.
// All implementations must embed UnimplementedMutexServer
// for forward compatibility.
//
// Mutex is the peer-to-peer transport for Ricart-Agrawala distributed
// mutual exclusion. Nodes call each other on the same gRPC port that serves
// the client DB API.
//
// The paper's REQUEST/REPLY message pair maps onto one blocking RPC: the
// call carries the REQUEST; the response IS the grant. A node that must
// defer (it holds the CS, or its own request has priority) simply does not
// respond until it exits the critical section.
type MutexServer interface {
	RequestCS(context.Context, *RequestCSRequest) (*RequestCSResponse, error)
	mustEmbedUnimplementedMutexServer()
}

// UnimplementedMutexServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMutexServer struct{}

func (UnimplementedMutexServer) RequestCS(context.Context, *RequestCSRequest) (*RequestCSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestCS not implemented")
}
func (UnimplementedMutexServer) mustEmbedUnimplementedMutexServer() {}
func (UnimplementedMutexServer) testEmbeddedByValue()               {}

// UnsafeMutexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MutexServer will
// result in compilation errors.
type UnsafeMutexServer interface {
	mustEmbedUnimplementedMutexServer()
}

func RegisterMutexServer(s grpc.ServiceRegistrar, srv MutexServer) {
	// If the following call panics, it indicates UnimplementedMutexServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Mutex_ServiceDesc, srv)
}

func _Mutex_RequestCS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutexServer).RequestCS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Mutex_RequestCS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutexServer).RequestCS(ctx, req.(*RequestCSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Mutex_ServiceDesc is the grpc.ServiceDesc for Mutex service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mutex_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mutex.v1.Mutex",
	HandlerType: (*MutexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestCS",
			Handler:    _Mutex_RequestCS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mutex/v1/mutex.proto",
}
