// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: mutex/v1/mutex.proto

package mutexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCSRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Requesting node's id. Unique ids break Lamport-timestamp ties,
	// extending the clock's partial order to the total order the algorithm
	// needs.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The requester's Lamport timestamp, fixed once per request — every peer
	// receives the same (lamport_time, node_id) pair.
	LamportTime   uint64 `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCSRequest) Reset() {
	*x = RequestCSRequest{}
	mi := &file_mutex_v1_mutex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCSRequest) ProtoMessage() {}

func (x *RequestCSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mutex_v1_mutex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCSRequest.ProtoReflect.Descriptor instead.
func (*RequestCSRequest) Descriptor() ([]byte, []int) {
	return file_mutex_v1_mutex_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCSRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RequestCSRequest) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type RequestCSResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Granter's clock at the moment of the grant (a message send event).
	LamportTime   uint64 `protobuf:"varint,1,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCSResponse) Reset() {
	*x = RequestCSResponse{}
	mi := &file_mutex_v1_mutex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCSResponse) ProtoMessage() {}

func (x *RequestCSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mutex_v1_mutex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCSResponse.ProtoReflect.Descriptor instead.
func (*RequestCSResponse) Descriptor() ([]byte, []int) {
	return file_mutex_v1_mutex_proto_rawDescGZIP(), []int{1}
}

func (x *RequestCSResponse) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

var File_mutex_v1_mutex_proto protoreflect.FileDescriptor

const file_mutex_v1_mutex_proto_rawDesc = "" +
	"\n" +
	"\x14mutex/v1/mutex.proto\x12\bmutex.v1\"N\n" +
	"\x10RequestCSRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12!\n" +
	"\flamport_time\x18\x02 \x01(\x04R\vlamportTime\"6\n" +
	"\x11RequestCSResponse\x12!\n" +
	"\flamport_time\x18\x01 \x01(\x04R\vlamportTime2M\n" +
	"\x05Mutex\x12D\n" +
	"\tRequestCS\x12\x1a.mutex.v1.RequestCSRequest\x1a\x1b.mutex.v1.RequestCSResponseBNZLgithub.com/code-lucasgabriel/raft-replicated-db/internal/pb/mutex/v1;mutexv1b\x06proto3"

var (
	file_mutex_v1_mutex_proto_rawDescOnce sync.Once
	file_mutex_v1_mutex_proto_rawDescData []byte
)

func file_mutex_v1_mutex_proto_rawDescGZIP() []byte {
	file_mutex_v1_mutex_proto_rawDescOnce.Do(func() {
		file_mutex_v1_mutex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mutex_v1_mutex_proto_rawDesc), len(file_mutex_v1_mutex_proto_rawDesc)))
	})
	return file_mutex_v1_mutex_proto_rawDescData
}

var file_mutex_v1_mutex_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mutex_v1_mutex_proto_goTypes = []any{
	(*RequestCSRequest)(nil),  // 0: mutex.v1.RequestCSRequest
	(*RequestCSResponse)(nil), // 1: mutex.v1.RequestCSResponse
}
var file_mutex_v1_mutex_proto_depIdxs = []int32{
	0, // 0: mutex.v1.Mutex.RequestCS:input_type -> mutex.v1.RequestCSRequest
	1, // 1: mutex.v1.Mutex.RequestCS:output_type -> mutex.v1.RequestCSResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mutex_v1_mutex_proto_init() }
func file_mutex_v1_mutex_proto_init() {
	if File_mutex_v1_mutex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mutex_v1_mutex_proto_rawDesc), len(file_mutex_v1_mutex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mutex_v1_mutex_proto_goTypes,
		DependencyIndexes: file_mutex_v1_mutex_proto_depIdxs,
		MessageInfos:      file_mutex_v1_mutex_proto_msgTypes,
	}.Build()
	File_mutex_v1_mutex_proto = out.File
	file_mutex_v1_mutex_proto_goTypes = nil
	file_mutex_v1_mutex_proto_depIdxs = nil
}
