// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: db/v1/db.proto

package dbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LamportTime   uint64                 `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_db_v1_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type GetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Value []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	// Populated when this node served a stale read or could not serve the read.
	LeaderHint    string `protobuf:"bytes,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	LamportTime   uint64 `protobuf:"varint,4,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_db_v1_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *GetResponse) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LamportTime   uint64                 `protobuf:"varint,3,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_db_v1_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type PutResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty when accepted by the leader; set to the leader's node id otherwise.
	LeaderHint    string `protobuf:"bytes,1,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	LamportTime   uint64 `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_db_v1_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *PutResponse) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LamportTime   uint64                 `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_db_v1_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderHint    string                 `protobuf:"bytes,1,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	LamportTime   uint64                 `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_db_v1_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetLeaderHint() string {
	if x != nil {
		return x.LeaderHint
	}
	return ""
}

func (x *DeleteResponse) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type IncrRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Amount to add; the value must be (or become) a decimal integer string.
	Delta int64 `protobuf:"varint,2,opt,name=delta,proto3" json:"delta,omitempty"`
	// Skip the distributed lock. Exists for two reasons: (1) the lost-update
	// experiment — concurrent unsafe increments race on read-modify-write;
	// (2) internal forwarding — a node already holding the CS forwards the
	// increment to the leader with unsafe=true, so the leader executes it
	// under the origin node's lock instead of deadlocking on a second one.
	Unsafe        bool   `protobuf:"varint,3,opt,name=unsafe,proto3" json:"unsafe,omitempty"`
	LamportTime   uint64 `protobuf:"varint,4,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrRequest) Reset() {
	*x = IncrRequest{}
	mi := &file_db_v1_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrRequest) ProtoMessage() {}

func (x *IncrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrRequest.ProtoReflect.Descriptor instead.
func (*IncrRequest) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{6}
}

func (x *IncrRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *IncrRequest) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *IncrRequest) GetUnsafe() bool {
	if x != nil {
		return x.Unsafe
	}
	return false
}

func (x *IncrRequest) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

type IncrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewValue      int64                  `protobuf:"varint,1,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	LamportTime   uint64                 `protobuf:"varint,2,opt,name=lamport_time,json=lamportTime,proto3" json:"lamport_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrResponse) Reset() {
	*x = IncrResponse{}
	mi := &file_db_v1_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrResponse) ProtoMessage() {}

func (x *IncrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_v1_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrResponse.ProtoReflect.Descriptor instead.
func (*IncrResponse) Descriptor() ([]byte, []int) {
	return file_db_v1_db_proto_rawDescGZIP(), []int{7}
}

func (x *IncrResponse) GetNewValue() int64 {
	if x != nil {
		return x.NewValue
	}
	return 0
}

func (x *IncrResponse) GetLamportTime() uint64 {
	if x != nil {
		return x.LamportTime
	}
	return 0
}

var File_db_v1_db_proto protoreflect.FileDescriptor

const file_db_v1_db_proto_rawDesc = "" +
	"\n" +
	"\x0edb/v1/db.proto\x12\x05db.v1\"A\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\flamport_time\x18\x02 \x01(\x04R\vlamportTime\"}\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\tR\n" +
	"leaderHint\x12!\n" +
	"\flamport_time\x18\x04 \x01(\x04R\vlamportTime\"W\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12!\n" +
	"\flamport_time\x18\x03 \x01(\x04R\vlamportTime\"Q\n" +
	"\vPutResponse\x12\x1f\n" +
	"\vleader_hint\x18\x01 \x01(\tR\n" +
	"leaderHint\x12!\n" +
	"\flamport_time\x18\x02 \x01(\x04R\vlamportTime\"D\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\flamport_time\x18\x02 \x01(\x04R\vlamportTime\"T\n" +
	"\x0eDeleteResponse\x12\x1f\n" +
	"\vleader_hint\x18\x01 \x01(\tR\n" +
	"leaderHint\x12!\n" +
	"\flamport_time\x18\x02 \x01(\x04R\vlamportTime\"p\n" +
	"\vIncrRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\x03R\x05delta\x12\x16\n" +
	"\x06unsafe\x18\x03 \x01(\bR\x06unsafe\x12!\n" +
	"\flamport_time\x18\x04 \x01(\x04R\vlamportTime\"N\n" +
	"\fIncrResponse\x12\x1b\n" +
	"\tnew_value\x18\x01 \x01(\x03R\bnewValue\x12!\n" +
	"\flamport_time\x18\x02 \x01(\x04R\vlamportTime2\xc8\x01\n" +
	"\x02DB\x12,\n" +
	"\x03Get\x12\x11.db.v1.GetRequest\x1a\x12.db.v1.GetResponse\x12,\n" +
	"\x03Put\x12\x11.db.v1.PutRequest\x1a\x12.db.v1.PutResponse\x125\n" +
	"\x06Delete\x12\x14.db.v1.DeleteRequest\x1a\x15.db.v1.DeleteResponse\x12/\n" +
	"\x04Incr\x12\x12.db.v1.IncrRequest\x1a\x13.db.v1.IncrResponseBHZFgithub.com/code-lucasgabriel/raft-replicated-db/internal/pb/db/v1;dbv1b\x06proto3"

var (
	file_db_v1_db_proto_rawDescOnce sync.Once
	file_db_v1_db_proto_rawDescData []byte
)

func file_db_v1_db_proto_rawDescGZIP() []byte {
	file_db_v1_db_proto_rawDescOnce.Do(func() {
		file_db_v1_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_v1_db_proto_rawDesc), len(file_db_v1_db_proto_rawDesc)))
	})
	return file_db_v1_db_proto_rawDescData
}

var file_db_v1_db_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_db_v1_db_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: db.v1.GetRequest
	(*GetResponse)(nil),    // 1: db.v1.GetResponse
	(*PutRequest)(nil),     // 2: db.v1.PutRequest
	(*PutResponse)(nil),    // 3: db.v1.PutResponse
	(*DeleteRequest)(nil),  // 4: db.v1.DeleteRequest
	(*DeleteResponse)(nil), // 5: db.v1.DeleteResponse
	(*IncrRequest)(nil),    // 6: db.v1.IncrRequest
	(*IncrResponse)(nil),   // 7: db.v1.IncrResponse
}
var file_db_v1_db_proto_depIdxs = []int32{
	0, // 0: db.v1.DB.Get:input_type -> db.v1.GetRequest
	2, // 1: db.v1.DB.Put:input_type -> db.v1.PutRequest
	4, // 2: db.v1.DB.Delete:input_type -> db.v1.DeleteRequest
	6, // 3: db.v1.DB.Incr:input_type -> db.v1.IncrRequest
	1, // 4: db.v1.DB.Get:output_type -> db.v1.GetResponse
	3, // 5: db.v1.DB.Put:output_type -> db.v1.PutResponse
	5, // 6: db.v1.DB.Delete:output_type -> db.v1.DeleteResponse
	7, // 7: db.v1.DB.Incr:output_type -> db.v1.IncrResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_db_v1_db_proto_init() }
func file_db_v1_db_proto_init() {
	if File_db_v1_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_v1_db_proto_rawDesc), len(file_db_v1_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_v1_db_proto_goTypes,
		DependencyIndexes: file_db_v1_db_proto_depIdxs,
		MessageInfos:      file_db_v1_db_proto_msgTypes,
	}.Build()
	File_db_v1_db_proto = out.File
	file_db_v1_db_proto_goTypes = nil
	file_db_v1_db_proto_depIdxs = nil
}
